# Generated by Django 5.0.6 on 2024-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('es_admin', models.BooleanField(default=False)),
                ('pnombre', models.CharField(max_length=255)),
                ('snombre', models.CharField(blank=True, max_length=255, null=True)),
                ('papellido', models.CharField(max_length=255)),
                ('sapellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
