# Generated by Django 5.0.6 on 2024-07-03 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_usuarios_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_reporte', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('datos_motivo', models.CharField(max_length=255)),
                ('cuerpo_reporte', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
