# Generated by Django 5.0.6 on 2024-06-26 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_alter_usuarios_last_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=255)),
                ('nombre_libro', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('resumen', models.TextField(default='No hay resumen disponible aún')),
                ('disponible_para_venta', models.BooleanField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portada', models.ImageField(upload_to='portadas/')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.categoria')),
            ],
            options={
                'db_table': 'libros',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nro_items', models.IntegerField()),
                ('nombre_items', models.CharField(max_length=1000)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuarios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orde_de_compra',
            },
        ),
    ]
