# Generated by Django 5.0.6 on 2024-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='precio_total',
            field=models.IntegerField(),
        ),
    ]
