# Generated by Django 5.0.6 on 2024-07-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_libro_precio_alter_ordendecompra_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='estado',
            field=models.CharField(default='pendiente', max_length=255),
        ),
    ]
