# Generated by Django 5.0.6 on 2024-07-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_ordendecompra_estado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordendecompra',
            table=None,
        ),
    ]
