# Generated by Django 5.0.6 on 2024-07-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_ordendecompra_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendecompra',
            old_name='usuarios_id',
            new_name='usuarios_id_id',
        ),
    ]
