# Generated by Django 5.0.6 on 2024-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_publicaciones/'),
        ),
    ]
