"""
Django settings for Project_Blogsillo project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SITE_ID = 1  # Puedes usar cualquier valor que exista en la base de datos de la tabla django_site

#Tabla designada para los usuarios, tanto administradores como clientes.
AUTH_USER_MODEL = 'Users.Usuarios'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-21(b^-8p@e&ni5*-=leu8z+#lch3)h%jb7c7r$$!p*)r6w1!j('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [             #Aqui instalas las aplicaciones
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Inicio',
    'Users',
    'payments_mercadopago',
    'Tienda',
    'Resumenes',
    'Criticas',
    'Publicar',
     
]

LOGIN_REDIRECT_URL = '/admin/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project_Blogsillo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'Inicio', 'templates'),
            os.path.join(BASE_DIR, 'Users', 'templates'),
            os.path.join(BASE_DIR, 'Tienda', 'templates'),
            os.path.join(BASE_DIR, 'Publicar', 'templates'),


        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project_Blogsillo.wsgi.application'

PAYMENT_VARIANTS = {
    # ...
    'MercadoPago': ('payments_mercadopago.MercadoPagoProvider', {
        'access_token': 'TEST-1886435135389237-071418-277e6f35cfeab2d5455ee6de4b879e2b-155563340',
        'sandbox_mode': True,  # Cambia a False para producción
    })
}
CHECKOUT_PAYMENT_CHOICES = [('MercadoPago', 'Mercado Pago')]
PAYMENT_HOST = 'localhost:8000'
MERCADOPAGO_ACCESS_TOKEN = 'TEST-1886435135389237-071418-277e6f35cfeab2d5455ee6de4b879e2b-155563340'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bd_blogsillo',
        'USER':'root',
        'PASSWORD':'',
        'HOST':'localhost',
        'PORT':'3306',
     }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-eu'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Media files (Uploaded files like user uploads)
MEDIA_URL = '/media/'  # URL base para servir archivos multimedia
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Ruta local donde se almacenarán los archivos multimedia

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
